//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("ApplyForFullMember")]
    //转正申请
    public partial class ApplyForFullMember
    {
       
        [Key]
        public int Id { get; set; }
        //员工编号
        public string EmployeeId { get; set; }
        //是否购买社保
        public Nullable<bool> IsBuySS { get; set; }
        //试用期结束时
        public Nullable<System.DateTime> ProbationEndDate { get; set; }
        //试用期个人总结
        public string ProbationPersonalSummary { get; set; }
        //申请时间
        public Nullable<System.DateTime> ApplicationDate { get; set; }
        //是否删除
        public Nullable<bool> IsPass { get; set; }
        public Nullable<bool> IsApproval { get; set; }
    }
}
