//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("CandidateInfo")]
    //考生信息
    public partial class CandidateInfo
    {
        [Key]
        //考号
        public string CandidateNumber { get; set; }
        //报考学号
        public int Examination { get; set; }
        //学员学号
        public string StudentID { get; set; }
        /// <summary>
        /// 是否为重考
        /// </summary>
        public bool IsReExam { get; set; }
        public string Paper { get; set; }

        public string ComputerPaper { get; set; }

        public int ClassId { get; set; }


    }
}
