//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("ChooseAnswerSheet")]
    //选择题答卷
    public partial class ChooseAnswerSheet
    {
        [Key]
        public int Id { get; set; }
        //考生
        public string CandidateInfo { get; set; }
        //题目
        public Nullable<int> Topic { get; set; }
        //答案
        public string Answer { get; set; }
    
    }
}
