//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("Classroomequipment")]
    //教室设备
    public partial class Classroomequipment
    {
        [Key]
        public int ID { get; set; }
        //设备id
        public Nullable<int> Device_ID { get; set; }
        //教室id
        public Nullable<int> Classroom_Id { get; set; }
        //是否删除
        public Nullable<bool> IsDelete { get; set; }
        //添加时间
        public Nullable<System.DateTime> AddTime { get; set; }
    
    }
}
