//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table(name: "DaysOff")]//调休（申请）表
   public partial class DaysOff
    {
        [Key]
        public int Id { get; set; }
        public string EmployeeId { get; set; }//员工编号
        public Nullable<System.DateTime> StartTime { get; set; }//开始时间
        public Nullable<System.DateTime> EndTime { get; set; }//结束时间
        public Nullable<decimal> Duration { get; set; }//时长
        public string LeaveReason { get; set; }//调休理由
        public string Image { get; set; }//图片
        public Nullable<bool> IsPassYear { get; set; }//是否过了年限
        public Nullable<bool> IsPass { get; set; }//申请是否通过
        public Nullable<bool> IsApproval { get; set; }//是否审批

    }
}
