//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table(name: "Detailsofconsignments")]
    //学员领用物资详情
    public partial class Detailsofconsignments
    {
        [Key]
        public int ID { get; set; }
        //退学ID
        public Nullable<int> AppDro_ID { get; set; }
        //学员物——ID
        public Nullable<int> Stu_Id { get; set; }
        //备注
        public string Remarks { get; set; }
        //是否禁用
        public Nullable<bool> IsDelete { get; set; }
        //添加时间
        public Nullable<System.DateTime> Addtime { get; set; }
    
    }
}
