//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table(name: "Detailedpayment")]
    //缴费明细
    public partial class Detailedpayment
    {
        [Key]
        public int ID { get; set; }
        //学员缴费id
        public Nullable<int> PayID { get; set; }
        //费用价格id
        public Nullable<int> CostpriceID { get; set; }
        //是否删除
        public Nullable<bool> Dateofregistration { get; set; }
        //添加时间
        public Nullable<System.DateTime> Addtime { get; set; }
    
    }
}
