//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table(name: "DormitoryCharging")]
    //宿舍充电
    public partial class DormitoryCharging
    {
        [Key]
        public int ID { get; set; }
        //是否删除
        public Nullable<bool> Dateofregistration { get; set; }
        //备注
        public string Remarks { get; set; }
        //日期
        public Nullable<System.DateTime> Departmentname { get; set; }
        //寝室
        public Nullable<int> Dorm { get; set; }
        //充电金额
        public Nullable<decimal> Chargingamount { get; set; }
        //支付类型
        public Nullable<int> Paymenttype { get; set; }
    }
}
