//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table(name: "HomeWorkFinishRate")]
    //学员作业提交情况
    public partial class HomeWorkFinishRate
    {
        [Key]
        public int ID { get; set; }
        //上机作业
        public Nullable<bool> ClassroomHomeWork { get; set; }
        //课后作业
        public Nullable<bool> AfterClassHomeWork { get; set; }
        //批注
        public string Notes { get; set; }
        //检查时间
        public Nullable<System.DateTime> CheckDate { get; set; }
        //是否删除
        public Nullable<bool> IsDel { get; set; }
        //作业检查人
        public Nullable<int> ChekTeacher { get; set; }
        //学员
        public string StudentNumber { get; set; }
        public DateTime ReleaseDate { get; set; }//作业布置的时间



    }
}
