//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table(name: "IsGoodOrBad")]
    //报溢报损
    public partial class IsGoodOrBad
    {
        [Key]
        public int Id { get; set; }
        //盘点id
        public Nullable<int> Check_Id { get; set; }
        //物品id
        public Nullable<int> Goods_Id { get; set; }
        //发现时间
        public Nullable<System.DateTime> FindDate { get; set; }
        //报溢报损
        public Nullable<bool> IsOK { get; set; }
        //原因
        public string Cause { get; set; }
        //是否删除
        public Nullable<bool> IsHandle { get; set; }
        //备注
        public string Note { get; set; }
    
        
    }
}
