//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table(name: "MachTestQuesBank")]
    //机试题库
    public partial class MachTestQuesBank
    {

        [Key]
        public int ID { get; set; }
        //标题
        public string Title { get; set; }
        //存放地址
        public string SaveURL { get; set; }
        //命题人
        public Nullable<int> Proposition { get; set; }
        //难度级别
        public Nullable<int> Level { get; set; }
        //是否启用
        public Nullable<bool> IsUsing { get; set; }
        //创建时间
        public Nullable<System.DateTime> CreateDate { get; set; }
        //所属课程
        public Nullable<int> Course { get; set; }
        public int Grand { get; set; }


    }
}
