//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table(name: "NurseTeamonDuty")]
    //护卫队执勤
    public partial class NurseTeamonDuty
    {
        [Key]
        public int ID { get; set; }
        //日期
        public string Daste { get; set; }
        //早开门
        public string Openthedoorearly { get; set; }
        //晚开门
        public string Openlate { get; set; }
        //上午执勤
        public string Morningduty { get; set; }
        //中午执勤
        public string Ondutyatnoon { get; set; }
        //下午执勤
        public string Theafternoon { get; set; }
        //晚大门职守
        public string Nightgateguard { get; set; }
        //是否删除
        public Nullable<bool> Dateofregistration { get; set; }
        //添加时间
        public Nullable<System.DateTime> Addtime { get; set; }
        //备注
        public string Remarks { get; set; }
    }
}
