//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table(name: "OvertimeRecord")]
    //加班记录表
    public partial class OvertimeRecord
    {
        [Key]
        public int Id { get; set; }
        //员工编号
        public string EmployeeId { get; set; }
        public Nullable<System.DateTime> YearAndMonth { get; set; }//年月份
        //开始时间
        public Nullable<System.DateTime> StartTime { get; set; }
        //结束时间
        public Nullable<System.DateTime> EndTime { get; set; }
        //加班时长
        public Nullable<decimal> Duration { get; set; }
        //加班原因
        public string OvertimeReason { get; set; }
        //是否不调休
        public Nullable<bool> IsNoDaysOff { get; set; }
        //加班类型
        public int OvertimeTypeId { get; set; }
        ////是否过了年限
        //public Nullable<bool> IsPassYear { get; set; }
        //备注
        public string Remark { get; set; }
        ////是否禁用
        public Nullable<bool> IsPass { get; set; }
        //public Nullable<bool> IsApproval { get; set; }


    }
}
