//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table(name: "ParticiParticipants")]
    //打架情况参加学员
    public partial class ParticiParticipants
    {
        [Key]
        public int ID { get; set; }
        //学生学号
        public string StudentID { get; set; }
        //名称
        public string Name { get; set; }
        //原因
        public Nullable<int> Reason { get; set; }
        //是否删除
        public Nullable<bool> Dateofregistration { get; set; }
        public string Remarks { get; set; }
    
      
    }
}
