
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace SiliconValley.InformationSystem.Entity.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table(name: "Preferential")]
    //学费补助表
    public partial class Preferential
    {
        [Key]
        public int PID { get; set; }
        //学费补助名字
        public string PNmae { get; set; }
        //价格
        public decimal PPrice { get; set; }
    }
}
