//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    /// <summary>
    ///  宿舍物品价格表
    /// </summary>
    [Table(name: "Pricedormitoryarticles")]
    public partial class Pricedormitoryarticles
    {
        [Key]
        public int ID { get; set; }
        /// <summary>
        ///   //物品名称
        /// </summary>
        public string Nameofarticle { get; set; }
        /// <summary>
        ///  //单价
        /// </summary>
        public decimal Reentry { get; set; }
        /// <summary>
        ///  //备注
        /// </summary>
        public string Remarks { get; set; }

        /// <summary>
        ///  是否可用正常使用  true--正常使用，false--禁用
        /// </summary>
        public bool Dateofregistration { get; set; }
        /// <summary>
        ///       //添加时间
        /// </summary>
        public DateTime Addtime { get; set; }


    }
}
