//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table(name: "PrintGoodsApply")]
    //用印申请
    public partial class PrintGoodsApply
    {
        [Key]
        public int Id { get; set; }
        //用印部门
        public Nullable<int> DeptId { get; set; }
        //经办人
        public string Transactor { get; set; }
        //申请日期
        public Nullable<System.DateTime> ApplyDate { get; set; }
        //用印文件名称
        public string StampFileName { get; set; }
        //文件份数
        public Nullable<int> FileNum { get; set; }
        //文件类别
        public string FileType { get; set; }
        //加盖何种印章
        public string StamperType { get; set; }
        //备注
        public string Remark { get; set; }
    
       
    }
}
