//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table(name: "PurchaseType")]
    //采购类型
    public partial class PurchaseType
    {

        [Key]
        public int Id { get; set; }
        //类型名称
        public string TypeName { get; set; }
        //备注
        public string Rmark { get; set; }
        //是否删除
        public Nullable<bool> IsDelete { get; set; }


    }
}
