//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table(name: "SocialSecurityDetail")]
    public partial class SocialSecurityDetail
    {
        [Key]
        public int Id { get; set; }
        public string EmployeeId { get; set; }
        /// <summary>
        /// 缴费基数
        /// </summary>
        public Nullable<decimal> PaymentBase {get; set;}
        /// <summary>
        /// 大病保险
        /// </summary>
        public Nullable<decimal> SeriousIllnessInsurance { get; set; }
        /// <summary>
        /// 当前年月
        /// </summary>
        public Nullable<System.DateTime> CurrentYearAndMonth { get; set; }
        /// <summary>
        /// 补缴月份
        /// </summary>
        public Nullable<int> OverPayMonthNum { get; set; }
        /// <summary>
        /// 单位小计
        /// </summary>
        public Nullable<decimal> UnitTotal { get; set; }
        /// <summary>
        /// 个人小计
        /// </summary>
        public Nullable<decimal> PersonalTotal { get; set; }

        public string Remark { get; set; }
        public Nullable<bool> IsDel { get; set; }
    
    }
}
