//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table(name: "SocialSecProportion")]
    public partial class SocialSecProportion
    {
        [Key]
        public int Id { get; set; }
        /// <summary>
        /// 社保状态
        /// </summary>
        public string PayType { get; set; }
        /// <summary>
        /// 养老保险
        /// </summary>
        public Nullable<decimal> EndowmentInsurance { get; set; }
        /// <summary>
        /// 医疗保险
        /// </summary>
        public Nullable<decimal> MedicalInsurance { get; set; }
        /// <summary>
        /// 工伤保险
        /// </summary>
        public Nullable<decimal> WorkInjuryInsurance { get; set; }
        /// <summary>
        /// 生育保险
        /// </summary>
        public Nullable<decimal> MaternityInsurance { get; set; }
        /// <summary>
        /// 失业保险
        /// </summary>
        public Nullable<decimal> UnemploymentInsurance { get; set; }
        public Nullable<bool> IsDel { get; set; }
    }
}
